### ISSUE TITLE
Hang when verifying

### ISSUE THREAD

**Issue by pwnorbitals** [model-checking/kani#2888] opened 2023-11-21 11:35 UTC
The full log file is attached: [out.txt](https://github.com/model-checking/kani/files/13425772/out.txt). Here is the command used : `cargo kani --verbose --enable-unstable --output-format old --cbmc-args --verbosity 9 > out.log 2>&1`

It would seem that kani hangs indefinitely. I'm not sure how to get more output than this, please let me know how I could get more output to help troubleshoot :)

**Comment by adpaco-aws** [comment] 2023-11-22 18:11
Hi @pwnorbitals , thanks for opening this bug report!

Unfortunately, I'm not sure the output will be enough for us to work on a fix. Would it be possible for you to provide the source code (or another, possibly-reduced version of it) that causes this behavior?

**Comment by pwnorbitals** [comment] 2023-11-23 10:17
Unfortunately cannot publicly share the code, but would be OK to share it privately

**Comment by adpaco-aws** [comment] 2023-11-27 16:05
Hi @pwnorbitals , sorry for the late reply. Please share the code privately with me and I'll take a look.

**Comment by adpaco-aws** [comment] 2024-01-24 19:12
Hi @pwnorbitals , would you mind reaching out to me? It isn't necessary for you to share the code in private, but any details regarding what you're trying to do might be helpful for us to determine if this is a new issue or not.

**Comment by adpaco-aws** [comment] 2024-02-05 20:44
Update: @pwnorbitals shared with me an almost executable version of the code with two harnesses. Then, I was able to run the harnesses by making some minor changes.

**But I wasn’t able to reproduce the hanging behavior described above with Kani 0.45.0**. Both harnesses terminated within 15mins for me in a `m5a.4xlarge` instance. The second harness (i.e., the one where @pwnorbitals expected the problematic behavior) fails to verify because the unsupported intrinsic `sqrtf64` is reachable. Both harnesses seem quite similar in terms of complexity, at least according to stats shown by CBMC (VCCs, variables, etc.). It's also possible that these stats are considerably different because the code itself is much simpler.

I’ll close the issue because I wasn’t able to reproduce it. Please feel free to re-open this issue if you continue to encounter it with the latest Kani versions. FYI I’m including the relevant parts of the output for each harness below.

Output for `transform_into_frame`:

```
Runtime Symex: 2.81632s
size of program expression: 64795 steps
slicing removed 43266 assignments
Generated 3146 VCC(s), 936 remaining after simplification
Runtime Postprocess Equation: 0.0801212s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 1.48226s
Running propositional reduction
Post-processing
Runtime Post-process: 2.693e-05s
Solving with CaDiCaL 1.7.2
690151 variables, 2602562 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 2.19843s
Runtime decision procedure: 3.70513s
Running propositional reduction
Solving with CaDiCaL 1.7.2
690151 variables, 2602563 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 3.7646s
Runtime decision procedure: 3.7927s
Running propositional reduction
Solving with CaDiCaL 1.7.2
690151 variables, 2602564 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 72.8242s
Runtime decision procedure: 72.8618s
Running propositional reduction
Solving with CaDiCaL 1.7.2
690151 variables, 2602565 clauses
SAT checker: instance is UNSATISFIABLE
Runtime Solver: 761.65s
Runtime decision procedure: 761.704s

[...]

SUMMARY:
 ** 0 of 6573 failed (589 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 865.40094s

Complete - 1 successfully verified harnesses, 0 failures, 1 total.
```

Output for `check_combine_frame_transformations`:

```
Runtime Symex: 2.26625s
size of program expression: 53038 steps
slicing removed 34869 assignments
Generated 2837 VCC(s), 779 remaining after simplification
Runtime Postprocess Equation: 0.0639936s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 1.25489s
Running propositional reduction
Post-processing
Runtime Post-process: 2.003e-05s
Solving with CaDiCaL 1.7.2
551676 variables, 2177202 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 2.45933s
Runtime decision procedure: 3.73361s
Running propositional reduction
Solving with CaDiCaL 1.7.2
551676 variables, 2177203 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 26.5861s
Runtime decision procedure: 26.6119s
Running propositional reduction
Solving with CaDiCaL 1.7.2
551676 variables, 2177204 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 136.613s
Runtime decision procedure: 136.668s
Running propositional reduction
Solving with CaDiCaL 1.7.2
551676 variables, 2177205 clauses
SAT checker: instance is UNSATISFIABLE
Runtime Solver: 127.665s
Runtime decision procedure: 127.687s

[...]

SUMMARY:
 ** 1 of 6143 failed (6142 undetermined)
Failed Checks: 'sqrtf64' intrinsic is not currently supported by Kani. Please post your example at https://github.com/model-checking/kani/issues/new/choose
 File: "/github/home/.rustup/toolchains/nightly-2024-01-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/f64.rs", line 398, in std::f64::<impl f64>::sqrt

VERIFICATION:- FAILED
** WARNING: A Rust construct that is not currently supported by Kani was found to be reachable. Check the results for more details.
Verification Time: 310.36472s

Summary:
Verification failed for - kani_tests::check_combine_frame_transformations
Complete - 0 successfully verified harnesses, 1 failures, 1 total.
```

**Closed by adpaco-aws** 2024-02-05 20:44 UTC
Labels: [C] Bug, [E] Performance, T-User
