### ISSUE TITLE
Expected fat pointer panic during codegen of futures-executor crate

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#676] opened 2021-12-02 21:42 UTC
Steps to reproduce:
1. `cargo new foo`
2. `cd foo`
3. Add `futures-executor` to the dependencies in `Cargo.toml`:
 ```
[dependencies]
futures-executor = "0.3.18"
```
4. Run:
```
RUST_BACKTRACE=1 RUSTFLAGS=$(rmc-rustc --rmc-flags) RUSTC=$(rmc-rustc --rmc-path) cargo build --target x86_64-unknown-linux-gnu -j1
```

with RMC version: `7d0d4cfc6da`

I expected to see this happen: Verification successful

Instead, this happened:
```
thread 'rustc' panicked at 'Expected fat pointer, got:
Expr { value: Symbol { identifier: "_ZN98_$LT$futures_task..future_obj..LocalFutureObj$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$4poll17hb44d6457a5321e67E::1::var_3" }, typ: StructTag("tag-_9576340917947498652"), location: None }', compiler/rustc_codegen_rmc/src/codegen/statement.rs:378:25
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:107:14
   2: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_funcall
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:378:25
   3: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_terminator
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:77:17
   4: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_block
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/block.rs:30:28
   5: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:95:71
   6: core::iter::traits::iterator::Iterator::for_each::call::<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:733:29
   7: core::iter::adapters::map::map_fold::<(usize, &rustc_middle::mir::BasicBlockData), (rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), (), <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}>::{closure#0}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:84:21
   8: <core::iter::adapters::enumerate::Enumerate<_> as core::iter::traits::iterator::Iterator>::fold::enumerate::<&rustc_middle::mir::BasicBlockData, (), core::iter::adapters::map::map_fold<(usize, &rustc_middle::mir::BasicBlockData), (rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), (), <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}>::{closure#0}>::{closure#0}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:106:27
   9: <core::slice::iter::Iter<rustc_middle::mir::BasicBlockData> as core::iter::traits::iterator::Iterator>::fold::<(), <core::iter::adapters::enumerate::Enumerate<_> as core::iter::traits::iterator::Iterator>::fold::enumerate<&rustc_middle::mir::BasicBlockData, (), core::iter::adapters::map::map_fold<(usize, &rustc_middle::mir::BasicBlockData), (rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), (), <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}>::{closure#0}>::{closure#0}>
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:2171:21
  10: <core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::mir::BasicBlockData>> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::adapters::map::map_fold<(usize, &rustc_middle::mir::BasicBlockData), (rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), (), <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}>::{closure#0}>
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:112:9
  11: <core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::mir::BasicBlockData>>, <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::BasicBlock, &rustc_middle::mir::BasicBlockData), <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>::{closure#0}>
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:124:9
  12: <core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::mir::BasicBlockData>>, <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData>>::iter_enumerated::{closure#0}> as core::iter::traits::iterator::Iterator>::for_each::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{closure#1}>
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:736:9
  13: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:95:13
  14: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:109:35
  15: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:87:13
  16: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::try_with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
  17: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
  18: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:84:9
  19: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:108:25
  20: rustc_interface::passes::start_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1077:9
  21: <rustc_data_structures::profiling::VerboseTimingGuard>::run::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:644:9
  22: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  23: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1076:19
  24: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  25: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:42
  26: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:50
  27: rustc_middle::ty::context::tls::set_tlv::<rustc_middle::ty::context::tls::enter_context<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1762:9
  28: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:9
  29: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:9
  30: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  31: <rustc_interface::queries::Query<alloc::boxed::Box<dyn core::any::Any>>>::compute::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  32: rustc_driver::run_compiler::{closure#1}::{closure#2}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:409:13
  33: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  34: rustc_driver::run_compiler::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:314:22
  35: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:220:13
  36: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:971:5
  37: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:214:5
  38: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:236:12
  39: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:145:13
  40: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  41: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:109:5
  42: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:143:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=gotoc -Z trim-diagnostic-paths=no -Z human_readable_cgu_names -C embed-bitcode=no -C debuginfo=2 -C overflow-checks=on --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: <futures_task::LocalFutureObj<'_, T> as futures_core::Future>::poll
_ZN98_$LT$futures_task..future_obj..LocalFutureObj$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$4poll17hb44d6457a5321e67E
[RMC] current codegen location: Loc { file: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.18/src/future_obj.rs", function: None, line: 83, col: Some(5) }

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `futures-executor`
```

**Comment by zhassan-aws** [comment] 2022-03-16 23:01
Still crashes with the same message with `af11d38d93a` using `cargo kani --only-codegen`.

**Comment by celinval** [comment] 2022-05-24 22:13
I believe this is a limitation where we assumed that the first argument of a trait method is a reference to `self`. It happens that there are other things that can be used. From the [Rust reference](https://doc.rust-lang.org/reference/items/associated-items.html#methods), the following are accepted:

```
P = &'lt S | &'lt mut S | Box<S> | Rc<S> | Arc<S> | Pin<P>
S = Self | P
```

 In this specific case, I believe the issue is that `Pin<&mut Self>` is being used. I created the following test that reproduces the same issue:

```
use std::pin::Pin;

trait Trait {
    // Note: This also fails with Box.
    fn dummy(self: Pin<&mut Self>);
}

struct UnimplementedTrait {}

impl Trait for UnimplementedTrait {
    fn dummy(self: Pin<&mut Self>) {
        unimplemented!();
    }
}

#[kani::proof]
fn check_drop_in_poll() {
    let _future1 = UnimplementedTrait {};
}

pub struct LocalTraitObj<'a> {
    pub future: &'a dyn Trait,
}

impl<'a> Drop for LocalTraitObj<'a> {
    fn drop(&mut self) {}
}

```

**Comment by celinval** [comment] 2022-06-23 17:21
The solution I have for this issue is blocked by https://github.com/diffblue/cbmc/issues/6956. @tautschnig has already pushed a fix and now we just need to wait for it to be released.

**Closed** 2022-07-06 22:49 UTC
Labels: bug, MLP - Should Have
