### ISSUE TITLE
C-FFI: Support conversion of `Option<&T>` to `T*` in the CBMC linker

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#2152] opened 2023-01-24 18:08 UTC

**Comment by zhassan-aws** [comment] 2023-01-24 18:42
Is this a duplicate of #3?

**Comment by celinval** [comment] 2023-05-03 19:12
Yes. This is a duplicated of #3. Closing this in favor of the original issue.

**Closed by celinval** 2023-05-03 19:12 UTC
Labels: [C] Feature / Enhancement
