### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by miteshjain** [model-checking/kani#1952] opened 2022-11-30 01:20 UTC
Please provide a short summary of the issue, along with the information necessary to replicate.
Trying to use Kani on a kernel code (https://github.com/rivosinc/salus/). When adding a simple assert1(1 == 1), I see the following crash 
WARN kani_compiler::codegen_cprover_gotoc::compiler_interface Ignoring global ASM in crate salus. Verification results may be impacted.
WARN kani_compiler::codegen_cprover_gotoc::compiler_interface Ignoring global ASM in crate salus. Verification results may be impacted.
WARN kani_compiler::codegen_cprover_gotoc::compiler_interface Ignoring global ASM in crate salus. Verification results may be impacted.
WARN kani_compiler::codegen_cprover_gotoc::compiler_interface Ignoring global ASM in crate salus. Verification results may be impacted.
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `80`,
 right: `73`', kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:900:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::cast_sized_pointer_to_fat_pointer
   5: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::cast_to_unsized_expr
   6: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_pointer_cast
   7: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_rvalue
   8: kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_statement
   9: kani_compiler::codegen_cprover_gotoc::codegen::block::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_block
  10: kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_function
  11: std::thread::local::LocalKey<T>::with
  12: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  13: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  14: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  15: <rustc_interface::queries::Queries>::ongoing_codegen
  16: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  17: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Kani unexpectedly panicked during compilation.
If you are seeing this message, please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: core::result::Result::<guest_tracking::GuestVm<riscv_page_tables::Sv48x4>, guest_tracking::Error>::unwrap
_RNvMNtCseMykGesBPfI_4core6resultINtB2_6ResultINtNtCskt6jDOJtH5g_5salus14guest_tracking7GuestVmNtNtCskxGDdVAsH1K_17riscv_page_tables6sv48x46Sv48x4ENtBK_5ErrorE6unwrapBM_
[Kani] current codegen location: Loc { file: "/Users/luhark/.rustup/toolchains/nightly-2022-10-24-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs", function: None, start_line: 1107, start_col: Some(5), end_line: 1109, end_col: Some(23) }
warning: `salus` (bin "salus") generated 4 warnings
error: could not compile `salus`; 4 warnings emitted
Error: cargo exited with status exit status: 101

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl anyhow::Error>::msg
   2: kani_driver::session::KaniSession::run_terminal
   3: kani_driver::call_cargo::<impl kani_driver::session::KaniSession>::cargo_build
   4: kani_driver::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: _main

-->

using the following command line invocation:

```
<command>
cargo kani --enable-unstable --ignore-global-asm

with Kani version: cargo-kani 0.14.1

**Comment by zhassan-aws** [comment] 2022-11-30 04:43
Thanks for the bug report. Can you provide more details on the steps to reproduce?

I tried the following:
1. `git clone https://github.com/rivosinc/salus`
2. `cd salus`
3. Added a dummy proof to `src/main.rs`:
```diff
$ git diff
diff --git a/src/main.rs b/src/main.rs
index e2109c3..fe6e93d 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -602,3 +602,8 @@ extern "C" fn secondary_init(_hart_id: u64) {
     HOST_VM.wait().run(me.cpu_id().raw() as u64);
     poweroff();
 }
+
+#[kani::proof]
+fn check() {
+    assert!(1 == 1);
+}
```
4. Ran `cargo kani --enable-unstable --ignore-global-asm`
I didn't get the crash, but I got an error:
```
   Compiling salus v0.1.0 (/home/ubuntu/git/salus)
error: the `#[alloc_error_handler]` in this crate conflicts with allocation error handler in: std

error[E0152]: found duplicate lang item `panic_impl`
  --> src/main.rs:64:1
   |
64 | fn panic(info: &core::panic::PanicInfo) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `kani` depends on)
   = note: first definition in `std` loaded from /home/ubuntu/git/kani/target/kani/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0f413982240bd92b.rlib
   = note: second definition in the local crate (`salus`)

For more information about this error, try `rustc --explain E0152`.
Error: "Failed to compile crate."
error: could not compile `salus` due to 2 previous errors
Error: cargo exited with status exit status: 101
```
This was using the latest Kani version though (0.16.0).

**Comment by miteshjain** [comment] 2022-12-01 02:57
Hi Zayad,

I had to make the following changes to eliminate the redefinition of panic
and alloc_error in src/main.rs.

-#[panic_handler]
-fn panic(info: &core::panic::PanicInfo) -> ! {
-    println!("panic : {:?}", info);
-    abort();
+cfg_if::cfg_if! {
+    if #[cfg(kani)] {
+    } else {
+ #[panic_handler]
+ fn panic(info: &core::panic::PanicInfo) -> ! {
+    println!("panic : {:?}", info);
+    abort();
+ }
+    }
 }

+
+
 extern "C" {
     static _start: u8;
     static _stack_end: u8;
@@ -102,9 +110,14 @@ unsafe impl GlobalAlloc for GeneralGlobalAlloc {
 static GENERAL_ALLOCATOR: GeneralGlobalAlloc = GeneralGlobalAlloc;

 /// Aborts if the system hits an allocation error.
-#[alloc_error_handler]
-pub fn alloc_error(_layout: Layout) -> ! {
-    abort()
+cfg_if::cfg_if! {
+    if #[cfg(kani)] {
+    } else {
+ #[alloc_error_handler]
+ pub fn alloc_error(_layout: Layout) -> ! {
+    abort()
+ }
+    }
 }

**Comment by zhassan-aws** [comment] 2022-12-01 05:20
Thanks @miteshjain. I commented out the `panic` and `alloc_error` functions, and the dummy proof went through:
```
$ cargo kani --enable-unstable --ignore-global-asm
# -- snip --
RESULTS:

SUMMARY:
 ** 0 of 0 failed

VERIFICATION:- SUCCESSFUL
Verification Time: 0.012757201s
```
Can you try again with the latest version of Kani?

**Comment by zhassan-aws** [comment] 2022-12-06 17:54
Closing this issue as it seems to be resolved with the latest version of Kani. Feel free to repen if you're still running into issues.

**Closed by zhassan-aws** 2022-12-06 17:54 UTC
Labels: [C] Bug, [F] Crash, T-User
