### ISSUE TITLE
Compilation fail if dependency use kani

### ISSUE THREAD

**Issue by ProbablyClem** [model-checking/kani#3109] opened 2024-03-26 10:25 UTC
I'm trying to add kani checks to a project that has [zerocopy](https://crates.io/crates/zerocopy) in the dependecy tree, which uses kani itself.
When I try to run `cargo kani` in my crate, the build fails with errors building zerocoypy 
<img width="1009" alt="image" src="https://github.com/model-checking/kani/assets/45786362/340f5307-e83b-4003-8060-8e95d285f88c">

I also have this error with ring
<img width="1425" alt="image" src="https://github.com/model-checking/kani/assets/45786362/f1993d30-9b6b-4ffe-88e9-bcfa0775725d">

I guess thoses are the same issue : kani run checks on all the dependecies.
How can I only check the top level crate, to fix this issue ?

using the following command line invocation:

```
cargo kani
```

with Kani version: 0.48.O
Installed through cargo
On Apple M1

I have kani running successfully in another project, so I guess it's not an installation issue.
Thanks for your help !

**Comment by feliperodri** [comment] 2024-03-29 15:20
Hi, @ProbablyClem! Have you tried annotating your code with `#[cfg(kani)]`? Take a look at [how Firecracker set up their Kani harnesses](https://github.com/firecracker-microvm/firecracker/blob/8a1719fed1155599e640db924770b2e1e53f178c/src/vmm/src/devices/virtio/iovec.rs#L604). Could you share the code of your project? If we could take a look how the project is currently set up, we will be able to assist more.

**Comment by ProbablyClem** [comment] 2024-03-29 15:39
Thanks for your help !

My code is just this for this file
Unfortunatly, I cannot share the rest of the codebase since it's a proprietaty software.
We have a lot of dependencies and `zerocopy`, which is using kani itself, is one of them.
The compilation errors are showing errors in zerocopy, which is not the current crate but a dependency.

```rust
fn calculate_checksum(account_number: u64) -> String {
  ...
}

#[cfg(kani)]
mod kani {
    #[kani::proof]
    fn checksum_iban() {
        let account_number = kani::any::<u64>();
        let checksum = super::iban::calculate_checksum(account_number);
    }
}
```

**Comment by zhassan-aws** [comment] 2024-04-01 17:19
> Unfortunatly, I cannot share the rest of the codebase since it's a proprietaty software.

A minimal example that reproduces the issue would be helpful. I couldn't reproduce the error just through adding `zerocopy` as a dependency, so it seems that something else is at play, perhaps the way `zerocopy` is used in the package, or specific features that are used.

Here's what I tried:
1. `cargo new iss3109 && cd iss3109`
2. `cargo add zerocopy --features derive`
3. Replaced the contents of `main.rs` with the following:
```rust
use zerocopy::FromZeroes;

#[derive(FromZeroes)]
struct PacketHeader {
    src_port: [u8; 2],
    dst_port: [u8; 2],
    length: [u8; 2],
    checksum: [u8; 2],
}

#[kani::proof]
fn main() {
    let mut header = PacketHeader {
        src_port: 100u16.to_be_bytes(),
        dst_port: 200u16.to_be_bytes(),
        length: 300u16.to_be_bytes(),
        checksum: 400u16.to_be_bytes(),
    };

    header.zero();

    assert_eq!(header.src_port, [0, 0]);
    assert_eq!(header.dst_port, [0, 0]);
    assert_eq!(header.length, [0, 0]);
    assert_eq!(header.checksum, [0, 0]);
}
```
4. Ran `cargo kani`. This resulted in:
```
SUMMARY:
 ** 0 of 28 failed (1 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 0.12655857s
```

**Comment by ProbablyClem** [comment] 2024-04-02 07:57
Thanks for your help, 
I'll try to figure out what's the real issue then

**Comment by adpaco-aws** [comment] 2024-04-22 19:39
Hi @ProbablyClem , I'm going to close this issue since it seems stalled. May I suggest you reopen this issue when you find a reproducible example? Thanks!

**Closed by adpaco-aws** 2024-04-22 19:39 UTC
Labels: [C] Bug, T-User

**Comment by zi0Black** [comment] 2024-06-04 13:46
I have the same issue, I cannot build with Kani because of the Zerocopy import as dependency of a dependency. It is not the first time I have encountered this type of issue but never found a clear path for the solution, probably happens only in complex build environments (?).

```
error[E0433]: failed to resolve: use of undeclared crate or module `kani`
    --> /home/xcd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerocopy-0.7.34/src/lib.rs:8238:9
     |
8238 |         kani::assume(matches!(base.size_info, SizeInfo::SliceDst(..)));
     |         ^^^^ use of undeclared crate or module `kani`

error[E0433]: failed to resolve: use of undeclared crate or module `kani`
    --> /home/xcd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerocopy-0.7.34/src/lib.rs:8247:33
     |
8247 |         let layout: DstLayout = kani::any();
     |                                 ^^^^ use of undeclared crate or module `kani`

error: aborting due to 37 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `zerocopy` (lib) due to 38 previous errors
warning: build failed, waiting for other jobs to finish...
error: Failed to execute cargo (exit status: 101). Found 38 compilation errors.
```
