### ISSUE TITLE
Kani fails to detect use of a dangling pointer dereference in println

### ISSUE THREAD

**Issue by jsalzbergedu** [model-checking/kani#3235] opened 2024-06-06 21:18 UTC
Given the following code:
```rust
static mut MY_POINTER: Option<*mut i32> = None;

fn reference_dies() {
  let mut x: i32 = 2;
  unsafe {
    MY_POINTER = Some(&mut x as *mut i32);
    println!("use to ensure that compiler doesn't optimize to Some(0), {}", &mut x);
  }
}

#[kani::proof]
fn main() {
  reference_dies();
  unsafe {
    match MY_POINTER {
        None => { unreachable!() },
        Some(x) => { println!("My pointer, {}", *x) },
    }
  }
  assert!(true);
}
```
kani v0.45 with the following flags:

```bash
kani --enable-unstable --memory-safety-checks --extra-pointer-checks aliasing_ub_fail.rs
```
gives a verification success even though cbmc gives a verification failure for

```C
#include <memory.h>
#include <stdio.h>
static int *MY_POINTER = NULL;

void reference_dies() {
    int x = 2;
    MY_POINTER = &x;
    return;
}

int main() {
    reference_dies();
    printf("%d", *MY_POINTER);
    return 0;
}
```

I'm hesitant to call this a "bug", because it falls under a reference being used outside of its lifetime, but it seems like something Kani should be able to get...

**Comment by zhassan-aws** [comment] 2024-06-06 23:10
Miri correctly reports the issue:
```
$ cargo miri run
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
   Compiling ref_dies v0.1.0 (/home/ubuntu/examples/ref_dies)
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner target/miri/x86_64-unknown-linux-gnu/debug/ref_dies`
use to ensure that compiler doesn't optimize to Some(0), 2
error: Undefined Behavior: out-of-bounds pointer use: alloc838 has been freed, so this pointer is dangling
  --> src/main.rs:16:49
   |
16 |         Some(x) => { println!("My pointer, {}", *x) },
   |                                                 ^^ out-of-bounds pointer use: alloc838 has been freed, so this pointer is dangling
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
help: alloc838 was allocated here:
  --> src/main.rs:4:7
   |
4  |   let mut x: i32 = 2;
   |       ^^^^^
help: alloc838 was deallocated here:
  --> src/main.rs:9:1
   |
9  | }
   | ^
   = note: BACKTRACE (of the first span):
   = note: inside `main` at src/main.rs:16:49: 16:51
   = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

**Comment by zhassan-aws** [comment] 2024-06-06 23:16
I wonder if the issue is due to Kani's override of the `println` macro. If I replace the `println` statement with an explicit dereference, Kani correctly reports the bug:
```rust
static mut MY_POINTER: Option<*mut i32> = None;

fn reference_dies() {
  let mut x: i32 = 2;
  unsafe {
    MY_POINTER = Some(&mut x as *mut i32);
    println!("use to ensure that compiler doesn't optimize to Some(0), {}", &mut x);
  }
}

#[kani::proof]
fn main() {
  reference_dies();
  unsafe {
    match MY_POINTER {
        None => { unreachable!() },
        Some(x) => {
            //println!("My pointer, {}", *x)
            let _y = *x;
        },
    }
  }
  assert!(true);
}
```

```bash
$ cargo kani
Kani Rust Verifier 0.51.0 (cargo plugin)
   Compiling ref_dies v0.1.0 (/home/ubuntu/examples/ref_dies)
...


SUMMARY:
 ** 1 of 31 failed
Failed Checks: dereference failure: dead object
 File: "src/main.rs", line 19, in main

VERIFICATION:- FAILED
Verification Time: 0.14703128s
```

**Comment by zhassan-aws** [comment] 2024-06-07 17:41
> Yes, this is a limitation incurred by `println`. Unless we find a way to efficiently (!) evaluate format strings we wouldn't know what to do this this pointer.

Weirdly enough, Kani detects the error in this one even though the dereference also happens within a `println`:
```rust
#[kani::proof]
fn main() {
    let ptr = {
        let x = 5;
        &x as *const i32
    };
    //let x = unsafe { *ptr };
    println!("{}", unsafe { *ptr });
}
```

```
SUMMARY:
 ** 1 of 8 failed
Failed Checks: dereference failure: dead object
 File: "ss.rs", line 8, in main

VERIFICATION:- FAILED
Verification Time: 0.07627274s

```

**Comment by zhassan-aws** [comment] 2024-06-07 17:56
But it doesn't if the `println` itself is inside an unsafe block!!!
```rust
#[kani::proof]
fn main() {
    let ptr = {
        let x = 5;
        &x as *const i32
    };
    //let x = unsafe { *ptr };
    unsafe {
        println!("{}", *ptr);
    }
}
```

```
SUMMARY:
 ** 0 of 1 failed

VERIFICATION:- SUCCESSFUL
Verification Time: 0.061657175s
```
Similarly, the example in the OP fails if I move the `unsafe` inside the `println`:
```rust
#[kani::proof]
fn main() {
    reference_dies();
    let p = unsafe { MY_POINTER };
    match p {
        None => {
            unreachable!()
        }
        Some(x) => {
            println!("My pointer, {}", unsafe { *x })
            //let _y = *x;
        }
    }
    assert!(true);
}
```
```


SUMMARY:
 ** 1 of 25 failed
Failed Checks: dereference failure: dead object
 File: "src/main.rs", line 19, in main

VERIFICATION:- FAILED
Verification Time: 0.15355924s
```

**Comment by jsalzbergedu** [comment] 2024-06-13 19:57
For some reason kani marks this as passing too:
```rust
// kani-flags: -Zfunction-contracts

static mut MY_POINTER: Option<*mut i32> = None;

fn reference_dies() {
  let mut x: i32 = 2;
  unsafe {
    MY_POINTER = Some(&mut x as *mut i32);
    std::hint::black_box(format_args!("use to ensure that compiler doesn't optimize to Some(0), {}", &mut x));
  }
}

#[kani::proof]
fn main() {
  reference_dies();
  unsafe {
    match MY_POINTER {
        None => { unreachable!() },
        Some(x) => {
            std::hint::black_box(format_args!("My pointer, {}", *x));
        },
    }
  }
  assert!(true);
}
```

**Comment by celinval** [comment] 2024-06-20 00:09
I did some debugging, and I believe this issue is fixed by #3221.

A bit of background, I reduced the initial test case to two harnessed:

```rust
fn reference_dies() -> *mut i32 {
  let mut x: i32 = 2;
  &mut x as *mut i32
}

// This one fails
#[kani::proof]
fn local_unsafe() {
  let x = reference_dies();
  println!("My pointer, {}", unsafe { *x });
}

// This one initially passes
#[kani::proof]
unsafe fn general_unsafe() {
  let x = reference_dies();
  println!("My pointer, {}", *x);
}
```

Comparing their MIR, the `local_unsafe` reads the value into a temporary and passes the reference to the display function:

```asm
bb4: {                                                                      
  _8 = (*_1); # This will trigger the failure
  _7 = &_8;                                                               
  _6 = core::fmt::rt::Argument::<'_>::new_display::<i32>(_7) -> [return: bb2, unwind unreachable];
} 
```
while the `general_unsafe` was not using a temporary:
```asm
_7 = &(*_1); # Issue 2975
_6 = core::fmt::rt::Argument::<'_>::new_display::<i32>(_7) -> [return: bb2, unwind unreachable];
```

The de-reference followed by the new address operator wasn't triggering the error, which was recently fixed, but it is currently guarded with `-Z ptr-to-ref-cast-checks`. If you run Kani with that option, both verification will fail. :)

**Comment by celinval** [comment] 2024-06-20 00:10
Thanks to @artemagvanian, this is no longer an issue! We should add the test from this issue into our regression.

**Closed by celinval** 2024-06-20 00:10 UTC
Labels: [C] Bug, T-High Priority, [F] Soundness

**Comment by celinval** [comment] 2024-06-20 19:39
BTW, Kani still does not verify the debug / display code that is invoked by the display. So if the argument you pass is valid but has a dangling reference inside it, Kani will not detect that issue.
