### ISSUE TITLE
Kani panicked in codegen/rvalue

### ISSUE THREAD

**Issue by TomMD** [model-checking/kani#3318] opened 2024-07-02 22:23 UTC
```
thread 'rustc' panicked at kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:1317:9:error: internal compiler error: Kani unexpectedly panicked at panicked at kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:1317:9:
                                assertion `left == right` failed
                                  left: 48
                                 right: 41.


assertion `left == right` failed
  left: 48
 right: 41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: <der::error::Error as std::fmt::Debug>::fmt
_RNvXs9_NtCslefA7hYQHvl_3der5errorNtB5_5ErrorNtNtCscBmSNMcqgUz_4core3fmt5Debug3fmtCsg8FMlfzrjoY_7rslip10
[Kani] current codegen location: Loc { file: "$HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/der-0.7.9/src/error.rs", function: None, start_line: 18, start_col: Some(23), end_line: 18, end_col: Some(28) }
error: could not compile `rslip10` (lib test)
error: Failed to compile `rslip10` due to an internal compiler error.: error: internal compiler error: Kani unexpectedly panicked at panicked at kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:1317:9:
                                assertion `left == right` failed
                                  left: 48
                                 right: 41.
```

This is when running `cargo kani --package my_package --tests` and, evidently, kani has an issue with the latest `der` crate.

**Comment by adpaco-aws** [comment] 2024-07-03 15:27
Hi @TomMD , thanks for the bug report!

I haven't been able to reproduce this issue using the examples in the `der` documentation because they don't compile for me (i.e., the example [here](https://docs.rs/der/latest/der/)). I'll try looking for more examples later but it'd be really helpful if you could share some more information.

We don't need the reproducer to be minimal, but can you at least share with us what APIs from `der` you were using? Are you using any features from that crate? My understanding is the `rslip10` method is a test function you're defining. But if you were, for example, just deriving the `Encode` and `Decode` impls it shouldn't be too hard to write a reproducer on our own.

**Comment by adpaco-aws** [comment] 2024-07-03 18:42
Hey @TomMD , thanks so much for taking the time to submit a reproducer!

I'm able to confirm that Kani crashes with this code. It's not a problem if it uses other dependencies, for now we just need something to trigger the failure for debugging purposes. We will take it from here! 😄

**Comment by zhassan-aws** [comment] 2024-07-30 03:22
This is a duplicate of #2857 (same crash signature).

**Closed** 2024-08-01 21:18 UTC
Labels: [C] Bug, [F] Crash, T-User
