### ISSUE TITLE
first-steps-v2 coverage shows many uncovered lines

### ISSUE THREAD

**Issue by WesleyRosenblum** [model-checking/kani#1707] opened 2022-09-21 17:38 UTC
Generating a coverage report for the `first-steps-v2` file produces an output with many non-covered lines:

../kani/docs/src/tutorial/first-steps-v2
$ cargo kani --visualize --harness verify_success

<img width="303" alt="Screen Shot 2022-09-21 at 10 37 32 AM" src="https://user-images.githubusercontent.com/55108558/191573201-3d7e1f2e-15a1-4b1c-a425-f4f6c08bf7cc.png">

This was on an Mac M1 Pro

**Comment by franklee26** [comment] 2022-09-21 17:48
Ran into the same issue but I was unable to reproduce this after I cleaned the `target/` directory.

**Comment by celinval** [comment] 2024-06-21 18:40
Closing this since we are now deprecating `--visualize` option.

**Closed by celinval** 2024-06-21 18:40 UTC
Labels: [C] Bug
