### ISSUE TITLE
Intermittent failures in macOS CI jobs

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2973] opened 2024-01-12 19:46 UTC
**Proposed change:** Investigate the spurious failures in macOS CI jobs and attempt to fix if possible.

**Motivation:** This week some CI jobs running on macOS runners have been failing without a clear reason to do so. Some examples:
 * [This CI run](https://github.com/model-checking/kani/actions/runs/7451274260/job/20272013945) for #2968 
 * [This CI run](https://github.com/model-checking/kani/actions/runs/7505973104/job/20436374418) for #2967 (no code changes)
 * [This CI run](https://github.com/model-checking/kani/actions/runs/7506821091/job/20439086479) in `main` after we merged #2967 (again, no code changes)

In both cases, the processes are compiling a crate when they receive an abort signal. It's possible that we're hitting some resource limits in the runners themselves. But re-running the CI jobs a few times does the trick.

**Comment by kgantchev** [comment] 2024-01-15 05:59
Hi, I'm the CEO and co-founder of FlyCI.  You can also try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners.

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Exclusive M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```
 
They're up to 2x faster and up to 2x cheaper than GitHub's. We'll be very happy to have you on board.

**Comment by tautschnig** [comment] 2024-01-18 10:46
Adding another such failure: https://github.com/model-checking/kani/actions/runs/7568332070/job/20609324630?pr=2977. This looks a lot like what they saw in Miri: https://github.com/rust-lang/miri/issues/3255. Perhaps we should try to adapt https://github.com/rust-lang/miri/commit/0b79240ee540fffa1f21cd2efa44e241572f3899 for Kani.

**Comment by tautschnig** [comment] 2024-01-31 22:18
Resolving with the assumption that #2987 has fixed the problem, which is in line with the claims made in https://github.com/rust-lang/rust/issues/92173#issuecomment-1084957372 (that the problem is an XCode issue). We may have to re-open this issue if the problem isn't actually fixed by the OS upgrade.

**Closed by tautschnig** 2024-01-31 22:18 UTC
Labels: [C] Internal
