### ISSUE TITLE
Visualizer crashes on fixme_catch_unwind regression test 

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#276] opened 2021-06-29 21:21 UTC
```
ERROR: Skipping reachable function with invalid source location: {'function': 'fixme_catch_unwind::alloc6_init'}
ERROR: Skipping reachable function with invalid source location: {'function': 'fixme_catch_unwind::alloc4_init'}
ERROR: Skipping reachable function with invalid source location: {'function': 'fixme_catch_unwind::alloc3_init'}
Traceback (most recent call last):
  File "/usr/local/bin/cbmc-viewer", line 8, in <module>
    sys.exit(viewer())
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/viewer.py", line 213, in viewer
    report.report(config, sources, symbols, results, coverage, traces,
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/report.py", line 60, in report
    markup_trace.Trace(name, trace, symbols, properties, loops, snippets).dump(
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/markup_trace.py", line 103, in __init__
    self.prop_srcloc = format_srcloc(properties.get_srcloc(name)
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/markup_trace.py", line 153, in format_srcloc
    markup_link.link_text_to_file(fyle, fyle, from_file),
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/markup_link.py", line 51, in link_text_to_file
    path = path_to_file(to_file, from_file)
  File "/usr/local/lib/python3.9/site-packages/cbmc_viewer/markup_link.py", line 34, in path_to_file
    raise UserWarning(
UserWarning: /Users/dsn/ws/rmc/library/std/src/panicking.rs != ../../../../library/std/src/panicking.rs
```

**Comment by danielsn** [comment] 2021-06-29 21:23
```
╭─dsn@3c22fba61447 ~/ws/rmc/src/test/cbmc/Intrinsics ‹try-intrinsic*› 
╰─$ realpath ../../../../library/std/src/panicking.rs                                                                                                                                                                                                                          127 ↵
/Users/dsn/ws/rmc/library/std/src/panicking.rs
```

**Comment by vecchiot-aws** [comment] 2021-07-19 14:35
CMBC viewer [#46](https://github.com/awslabs/aws-viewer-for-cbmc/pull/46)

**Comment by zhassan-aws** [comment] 2022-03-15 20:07
Crash is no longer reproducible. Seems to be fixed by https://github.com/awslabs/aws-viewer-for-cbmc/pull/47. Closing this issue.

**Closed by zhassan-aws** 2022-03-15 20:07 UTC
